// export const CHANGE_USERNAME= 'CHANGE_USERNAME';
// export const CHANGE_PASSWORD= 'CHANGE_PASSWORD';

export const SET_USERNAME= 'SET_USERNAME';
export const SET_PASSWORD= 'SET_PASSWORD';
export const SET_EMAIL= 'SET_EMAIL';
